apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
    name: registry-creds
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: registry-creds
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registry-creds
subjects:
  - kind: ServiceAccount
    name: registry-creds
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-creds
  namespace: kube-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-creds
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: registry-creds
  template:
    metadata:
      labels:
        name: registry-creds
    spec:
      serviceAccountName: registry-creds
      containers:
      - image: upmcenterprises/awsecr-cred:1.10
        name: registry-creds
        imagePullPolicy: Always
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: registry-creds-ecr
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: registry-creds-ecr
                key: AWS_SECRET_ACCESS_KEY
          - name: awsaccount
            valueFrom:
              secretKeyRef:
                name: registry-creds-ecr
                key: aws-account
          - name: awsregion
            valueFrom:
              secretKeyRef:
                name: registry-creds-ecr
                key: aws-region
          - name: aws_assume_role
            valueFrom:
              secretKeyRef:
                name: registry-creds-ecr
                key: aws-assume-role
          # - name: DOCKER_PRIVATE_REGISTRY_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: registry-creds-dpr
          #       key: DOCKER_PRIVATE_REGISTRY_PASSWORD
          # - name: DOCKER_PRIVATE_REGISTRY_SERVER
          #   valueFrom:
          #     secretKeyRef:
          #       name: registry-creds-dpr
          #       key: DOCKER_PRIVATE_REGISTRY_SERVER
          # - name: DOCKER_PRIVATE_REGISTRY_USER
          #   valueFrom:
          #     secretKeyRef:
          #       name: registry-creds-dpr
          #       key: DOCKER_PRIVATE_REGISTRY_USER
          # - name: ACR_URL
          #   valueFrom:
          #     secretKeyRef:
          #       name: registry-creds-acr
          #       key: ACR_URL
          # - name: ACR_CLIENT_ID
          #   valueFrom:
          #     secretKeyRef:
          #       name: registry-creds-acr
          #       key: ACR_CLIENT_ID
          # - name: ACR_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: registry-creds-acr
          #       key: ACR_PASSWORD
      #   volumeMounts:
      #   - name: gcr-creds
      #     mountPath: "/root/.config/gcloud"
      #     readOnly: true
      # volumes:
      # - name: gcr-creds
      #   secret:
      #     secretName: registry-creds-gcr
